require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
use_frameworks!
platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

target 'SigndReactnativeSdkExample' do
  config = use_native_modules!
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  
  $static_framework = ['DoubleConversion',
    'FBLazyVector',
    'FBReactNativeSpec',
    'Flipper',
    'Flipper-Boost-iOSX',
    'Flipper-DoubleConversion',
    'Flipper-Fmt',
    'Flipper-Folly',
    'Flipper-Glog',
    'Flipper-PeerTalk',
    'Flipper-RSocket',
    'FlipperKit',
    'OpenSSL-Universal',
    'RCT-Folly',
    'RCTRequired',
    'RCTTypeSafety',
    'React',
    'React-Codegen',
    'React-Core',
    'React-CoreModules',
    'React-Fabric',
    'React-RCTActionSheet',
    'React-RCTAnimation',
    'React-RCTBlob',
    'React-RCTFabric',
    'React-RCTImage',
    'React-RCTLinking',
    'React-RCTNetwork',
    'React-RCTSettings',
    'React-RCTText',
    'React-RCTVibration',
    'React-callinvoker',
    'React-cxxreact',
    'React-graphics',
    'React-hermes',
    'React-jsi',
    'React-jsiexecutor',
    'React-jsinspector',
    'React-logger',
    'React-perflogger',
    'React-rncore',
    'React-runtimeexecutor',
    'ReactCommon',
    'Yoga',
    'YogaKit',
    'boost',
    'fmt',
    'glog',
    'hermes-engine'
  ]

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        if target.name == 'RCT-Folly'
          config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/fmt/include"
        end
      end
    end
  end
end
